/** Map existing Pack A theme_label values onto problem-hub tags. */

export const PROBLEM_TAG_IDS = [
  "sleep",
  "anxiety",
  "stress",
  "mood",
  "motivation",
  "faith",
];

export const THEME_LABEL_TO_TAGS = {
  "small irritations": ["stress"],
  imperfection: ["motivation", "mood"],
  "gentleness vs pressure": ["stress"],
  "rumination escalation": ["anxiety"],
  compassion: ["mood", "faith"],
  "perspective-taking": ["stress"],
  "prioritising conflict": ["stress"],
  "reactive communication": ["stress"],
  "gratitude for small": ["mood", "faith"],
  impatience: ["stress"],
  "over-identification with tasks": ["stress", "motivation"],
  "uncertainty tolerance": ["anxiety"],
  comparison: ["mood"],
  "receiving support": ["mood", "anxiety"],
  "single-tasking": ["stress", "motivation"],
  "need to be right": ["stress"],
  "holding grudges": ["mood"],
  "scarcity mindset": ["anxiety", "mood"],
  connection: ["faith", "mood"],
  "waiting to start": ["motivation"],
  "false emergencies": ["anxiety", "stress"],
  "drama resistance": ["stress"],
  "charitable interpretation": ["mood", "faith"],
  "rest guilt": ["sleep", "mood"],
  boundaries: ["stress"],
  "micro-completion": ["motivation"],
  "mental replay": ["anxiety", "sleep"],
  "work spillover": ["stress", "sleep"],
  listening: ["faith"],
  rush: ["stress"],
  judgement: ["mood"],
  overcommitment: ["stress"],
  "emotional patience": ["mood", "stress"],
  recognition: ["faith", "mood"],
  "embodied reset": ["stress", "anxiety"],
  "self-forgiveness": ["mood", "faith"],
  "mind-reading": ["anxiety"],
  "domestic perfection": ["stress"],
  "relational priority": ["mood"],
  grounding: ["anxiety", "stress"],
  "load shedding": ["stress"],
  "self-talk": ["mood"],
  "plans changing": ["anxiety", "motivation"],
  "inner critic": ["mood"],
  "over-scheduling": ["stress"],
  "mood awareness": ["mood"],
  "comfortable quiet": ["sleep", "anxiety"],
  "emotional labour": ["stress", "mood"],
  joy: ["mood"],
  "self-judgement at night": ["sleep", "mood"],
  play: ["mood", "motivation"],
  "expectation load": ["stress"],
  "body cues": ["sleep", "stress"],
  "image management": ["anxiety", "mood"],
  "impatience with delays": ["stress"],
  appreciation: ["mood", "faith"],
  "grievance collecting": ["mood"],
  "invisible progress": ["motivation"],
  attention: ["faith", "stress"],
  impermanence: ["faith", "anxiety"],
  "after conflict": ["mood"],
  "evening overload": ["sleep", "stress"],
  overwhelm: ["stress"],
  acceptance: ["mood", "faith"],
  "soft boundaries": ["stress"],
  "tunnel vision": ["anxiety", "stress"],
  "healing/patience": ["mood"],
  ego: ["stress"],
  waiting: ["anxiety", "motivation"],
  interruptions: ["stress"],
  "body tension": ["stress", "sleep"],
  "optimisation pressure": ["stress", "motivation"],
  attribution: ["mood"],
  "mental clutter": ["stress", "anxiety"],
  "showing up": ["motivation"],
  "specific thanks": ["mood", "faith"],
  catastrophising: ["anxiety"],
  "asking/delegation": ["stress"],
  lightness: ["mood"],
  limits: ["stress"],
  reset: ["motivation", "mood"],
  process: ["motivation"],
  receiving: ["mood"],
  "self-consciousness": ["anxiety", "mood"],
  "prep without panic": ["anxiety", "stress"],
  "waiting in line": ["stress"],
  pace: ["stress"],
  "joy permission": ["mood"],
  disengaging: ["stress"],
  maintenance: ["motivation"],
  "not knowing": ["anxiety", "faith"],
  priorities: ["motivation", "stress"],
  overstimulation: ["stress", "sleep"],
  "productivity myths": ["motivation", "stress"],
  "emotions passing": ["mood", "anxiety"],
  "pressure to perform": ["anxiety", "stress"],
  "old strategies": ["motivation"],
  closures: ["sleep", "mood"],
  "ordinary life": ["faith"],
  "fresh start": ["motivation"],
};

export function normalizeProblemTags(raw) {
  if (!Array.isArray(raw)) return [];
  return [...new Set(raw.filter((tag) => PROBLEM_TAG_IDS.includes(tag)))];
}

export function tagsForThemeLabel(label) {
  if (typeof label !== "string" || !label.trim()) return [];
  return normalizeProblemTags(THEME_LABEL_TO_TAGS[label.trim()] || []);
}

export function readingProblemTags(reading) {
  const fromItem = normalizeProblemTags(reading?.theme_tags || reading?.problemTags);
  if (fromItem.length) return fromItem;
  return tagsForThemeLabel(reading?.theme_label);
}
